require('core.plugin_config.treesitter')
-- require('core.plugin_config.nvim-tree')
require('core.plugin_config.lualine')
require('core.plugin_config.gitsigns')
require('core.plugin_config.whichkey')
require('core.plugin_config.lsp')
require('core.plugin_config.telescope')
require('core.plugin_config.outline')
require('core.plugin_config.oil')
